export const installed_blueprints = [
  //@BlueprintInsertion
{ name: 'Camera26819', human_name: 'Camera', access_route: 'Camera26819', icon: 'camera'},
{ name: 'CalendarView26818', human_name: 'Calendar View', access_route: 'CalendarView26818', icon: 'calendar'},
{ name: 'Maps26817', human_name: 'Maps', access_route: 'Maps26817', icon: 'map'},
{ name: 'Tutorial26816', human_name: 'Tutorial', access_route: 'Tutorial26816', icon: 'question-circle'},
{ name: 'Messaging26815', human_name: 'Messaging', access_route: 'Messaging26815', icon: 'comments'},
{ name: 'BlankScreen26813', human_name: 'Blank Screen', access_route: 'BlankScreen26813'},
{ name: 'BlankScreen26812', human_name: 'Blank Screen', access_route: 'BlankScreen26812'},
{ name: 'BlankScreen26811', human_name: 'Blank Screen', access_route: 'BlankScreen26811'},
{ name: 'BlankScreen26810', human_name: 'Blank Screen', access_route: 'BlankScreen26810'},
{ name: 'Contacts26807', human_name: 'Contacts', access_route: 'Contacts26807'},
{ name: 'EmailAuth26793', human_name: 'Email Auth', access_route: 'EmailAuth26793', icon: 'envelope-o'},
{ name: 'Maps26774', human_name: 'Maps', access_route: 'Maps26774', icon: 'map'},
{ name: 'Messaging26770', human_name: 'Messaging', access_route: 'Messaging26770', icon: 'comments'},
{ name: 'NotificationList26764', human_name: 'Notification List', access_route: 'NotificationList26764'},
{ name: 'Settings26753', human_name: 'Settings', access_route: 'Settings26753'},
{ name: 'SignIn126751', human_name: 'Sign In 1', access_route: 'SignIn126751'},
{ name: 'UserProfile26742', human_name: 'User Profile', access_route: 'UserProfile26742'},
{ name: 'BlankScreen26736', human_name: 'Blank Screen', access_route: 'BlankScreen26736'},
{ name: 'BlankScreen26735', human_name: 'Blank Screen', access_route: 'BlankScreen26735'},
{ name: 'BlankScreen26734', human_name: 'Blank Screen', access_route: 'BlankScreen26734'},
{ name: 'BlankScreen26733', human_name: 'Blank Screen', access_route: 'BlankScreen26733'},
{ name: 'Contacts26730', human_name: 'Contacts', access_route: 'Contacts26730'},
{ name: 'EmailAuth26716', human_name: 'Email Auth', access_route: 'EmailAuth26716', icon: 'envelope-o'},
{ name: 'Maps26697', human_name: 'Maps', access_route: 'Maps26697', icon: 'map'},
{ name: 'Messaging26693', human_name: 'Messaging', access_route: 'Messaging26693', icon: 'comments'},
{ name: 'NotificationList26687', human_name: 'Notification List', access_route: 'NotificationList26687'},
{ name: 'Settings26676', human_name: 'Settings', access_route: 'Settings26676'},
{ name: 'SignIn126674', human_name: 'Sign In 1', access_route: 'SignIn126674'},
{ name: 'UserProfile26665', human_name: 'User Profile', access_route: 'UserProfile26665'},
{ name: 'Messenger', human_name: 'Messenger', access_route: 'Messenger', icon: 'comments'},
{ name: 'Tutorial', human_name: 'Tutorial', access_route: 'Tutorial', icon: 'question-circle'},
{ name: 'Maps', human_name: 'Maps', access_route: 'Maps', icon: 'map'},
{ name: 'Calendar', human_name: 'Calendar', access_route: 'Calendar', icon: 'calendar'},
{ name: 'Camera', human_name: 'Camera', access_route: 'Camera', icon: 'camera'},
{ name: 'EmailAuth', human_name: 'EmailAuth', access_route: 'EmailAuth', icon: 'envelope-o'},

  // you can add more installed blueprints here
  // access route is the route nate given to navigator
];
